In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
import os
print(os.getcwd())

C:\Users\snowpiercer\Desktop\WeatherPredictionProject\notebooks

In [3]:

from pathlib import Path

ROOT = Path.cwd().parent

df = pd.read_csv(ROOT / "dataset" / "weather.csv")
df.head()

,Date,City,Temperature,Humidity,Pressure,Wind_Speed,Cloud_Cover,Weather,Rainfall
0,2011-12-25 03:00:00,Mysuru,13.7,81,925.7,24.12,57,Clear,0.0
1,2023-08-05 22:00:00,Anand,27.6,86,1002.0,40.68,100,Cloudy,0.0
2,2018-05-21 05:00:00,Bharuch,27.5,90,1002.3,46.80,0,Clear,0.0
3,2026-01-24 14:00:00,New_Delhi,16.4,46,996.7,37.08,6,Clear,0.0
4,2024-01-30 08:00:00,Mangaluru,25.6,64,1012.8,30.96,98,Cloudy,0.0

In [4]:
df.head(10)

,Date,City,Temperature,Humidity,Pressure,Wind_Speed,Cloud_Cover,Weather,Rainfall
0,2011-12-25 03:00:00,Mysuru,13.7,81,925.7,24.12,57,Clear,0.0
1,2023-08-05 22:00:00,Anand,27.6,86,1002.0,40.68,100,Cloudy,0.0
2,2018-05-21 05:00:00,Bharuch,27.5,90,1002.3,46.80,0,Clear,0.0
3,2026-01-24 14:00:00,New_Delhi,16.4,46,996.7,37.08,6,Clear,0.0
4,2024-01-30 08:00:00,Mangaluru,25.6,64,1012.8,30.96,98,Cloudy,0.0
5,2000-02-29 08:00:00,Amravati,20.5,53,975.8,7.56,0,Clear,0.0
6,2014-11-27 23:00:00,Wayanad,20.5,86,927.0,6.48,100,Cloudy,0.0
7,2016-06-03 22:00:00,Ahmedabad,34.0,35,998.2,30.96,1,Clear,0.0
8,2007-03-11 06:00:00,Udaipur,15.7,74,946.5,16.20,0,Clear,0.0
9,2014-05-19 15:00:00,Karimnagar,38.8,29,973.5,32.04,67,Rain,0.1

In [5]:
df.tail(10)

,Date,City,Temperature,Humidity,Pressure,Wind_Speed,Cloud_Cover,Weather,Rainfall
9990,2015-06-19 08:00:00,Bengaluru,21.1,89,907.9,76.32,100,Cloudy,0.0
9991,2020-11-29 09:00:00,Surat,27.4,47,1014.5,41.76,0,Clear,0.0
9992,2007-02-20 12:00:00,Wayanad,30.0,34,930.3,58.68,6,Clear,0.0
9993,2005-06-05 04:00:00,Nashik,22.6,90,940.0,52.20,31,Clear,0.0
9994,2021-06-10 04:00:00,Bharuch,27.5,88,999.8,54.00,37,Rain,0.1
9995,2023-11-27 11:00:00,Khammam,30.2,51,999.4,49.32,2,Clear,0.0
9996,2022-02-09 23:00:00,Rajkot,18.8,49,1001.0,28.08,0,Clear,0.0
9997,2008-08-07 16:00:00,Jodhpur,29.3,66,971.2,82.08,100,Cloudy,0.0
9998,2024-04-12 02:00:00,Udaipur,23.6,41,946.5,25.20,97,Cloudy,0.0
9999,2005-01-14 23:00:00,Solapur,21.1,42,959.3,36.36,0,Clear,0.0

In [6]:
df.shape

(10000, 9)

In [7]:
df.columns

Index(['Date', 'City', 'Temperature', 'Humidity', 'Pressure', 'Wind_Speed',
       'Cloud_Cover', 'Weather', 'Rainfall'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         10000 non-null  str
 1   City         10000 non-null  str
 2   Temperature  10000 non-null  float64
 3   Humidity     10000 non-null  int64
 4   Pressure     10000 non-null  float64
 5   Wind_Speed   10000 non-null  float64
 6   Cloud_Cover  10000 non-null  int64
 7   Weather      10000 non-null  str
 8   Rainfall     10000 non-null  float64
dtypes: float64(4), int64(2), str(3)
memory usage: 1015.6 KB

In [9]:
df.describe()

,Temperature,Humidity,Pressure,Wind_Speed,Cloud_Cover,Rainfall
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,25.645750,63.994900,972.071420,35.927892,47.826900,0.136400
std,5.568755,24.130108,31.309043,19.328231,41.995013,0.598546
min,2.300000,4.000000,891.900000,0.000000,0.000000,0.000000
25%,22.400000,45.000000,948.300000,22.320000,1.000000,0.000000
50%,25.700000,68.000000,977.200000,32.040000,42.000000,0.000000
75%,28.900000,85.000000,1000.700000,46.440000,97.000000,0.000000
max,44.100000,100.000000,1018.700000,132.480000,100.000000,23.200000

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.sample(10)

,Date,City,Temperature,Humidity,Pressure,Wind_Speed,Cloud_Cover,Weather,Rainfall
5861,2017-03-21 12:00:00,Barmer,35.0,17,992.1,59.40,0,Clear,0.0
2736,2018-02-04 17:00:00,Bharuch,32.2,18,1007.7,18.36,0,Clear,0.0
3787,2014-03-31 02:00:00,Khammam,26.0,53,992.7,24.12,1,Clear,0.0
3936,2011-11-22 14:00:00,Nashik,29.3,27,948.3,56.16,0,Clear,0.0
5108,2014-06-19 23:00:00,Ratnagiri,26.6,89,997.2,41.04,72,Rain,0.7
5594,2020-11-23 13:00:00,Kolhapur,30.2,39,951.2,31.32,76,Cloudy,0.0
2368,1996-04-26 12:00:00,Hyderabad,37.2,29,951.3,35.28,24,Clear,0.0
1833,2025-12-25 01:00:00,Chikkamagaluru,14.8,72,898.6,33.48,26,Clear,0.0
108,2013-10-15 20:00:00,Amravati,25.3,81,971.5,23.76,37,Clear,0.0
4990,2003-01-07 13:00:00,Bhavnagar,26.6,41,1013.8,49.32,0,Clear,0.0

In [12]:
df.memory_usage(deep=True)

Index             132
Date           270000
City           158580
Temperature     80000
Humidity        80000
Pressure        80000
Wind_Speed      80000
Cloud_Cover     80000
Weather        131263
Rainfall        80000
dtype: int64

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         10000 non-null  str
 1   City         10000 non-null  str
 2   Temperature  10000 non-null  float64
 3   Humidity     10000 non-null  int64
 4   Pressure     10000 non-null  float64
 5   Wind_Speed   10000 non-null  float64
 6   Cloud_Cover  10000 non-null  int64
 7   Weather      10000 non-null  str
 8   Rainfall     10000 non-null  float64
dtypes: float64(4), int64(2), str(3)
memory usage: 1015.6 KB

In [14]:
import sys
print(sys.executable)

C:\Users\snowpiercer\AppData\Local\Programs\Python\Python313\python.exe

In [15]:
import sys
print(sys.executable)

C:\Users\snowpiercer\AppData\Local\Programs\Python\Python313\python.exe