In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
from pathlib import Path

ROOT = Path.cwd().parent

df = pd.read_csv(ROOT / "dataset" / "weather_clean.csv")

In [3]:
df["Date"] = pd.to_datetime(
    df["Date"],
    format="mixed"
)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         10000 non-null  datetime64[us]
 1   City         10000 non-null  str
 2   Temperature  10000 non-null  float64
 3   Humidity     10000 non-null  int64
 4   Pressure     10000 non-null  float64
 5   Wind_Speed   10000 non-null  float64
 6   Cloud_Cover  10000 non-null  int64
 7   Weather      10000 non-null  str
 8   Rainfall     10000 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(2), str(2)
memory usage: 830.1 KB

In [5]:
print(df["City"].head())
print(df["City"].dtype)
print(df["City"].unique()[:10])

0       Mysuru
1        Anand
2      Bharuch
3    New_Delhi
4    Mangaluru
Name: City, dtype: str
str
<ArrowStringArray>
[    'Mysuru',      'Anand',    'Bharuch',  'New_Delhi',  'Mangaluru',
   'Amravati',    'Wayanad',  'Ahmedabad',    'Udaipur', 'Karimnagar']
Length: 10, dtype: str

In [6]:
df.head()

,Date,City,Temperature,Humidity,Pressure,Wind_Speed,Cloud_Cover,Weather,Rainfall
0,2011-12-25 03:00:00,Mysuru,13.7,81,925.7,24.12,57,Clear,0.0
1,2023-08-05 22:00:00,Anand,27.6,86,1002.0,40.68,100,Cloudy,0.0
2,2018-05-21 05:00:00,Bharuch,27.5,90,1002.3,46.80,0,Clear,0.0
3,2026-01-24 14:00:00,New_Delhi,16.4,46,996.7,37.08,6,Clear,0.0
4,2024-01-30 08:00:00,Mangaluru,25.6,64,1012.8,30.96,98,Cloudy,0.0

In [7]:
df["Date"] = pd.to_datetime(
    df["Date"],
    format="%d-%m-%Y %H:%M"
)

In [8]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Hour"] = df["Date"].dt.hour
df["DayOfWeek"] = df["Date"].dt.day_name()

In [9]:
df.head()

,Date,City,Temperature,Humidity,Pressure,Wind_Speed,Cloud_Cover,Weather,Rainfall,Year,Month,Day,Hour,DayOfWeek
0,2011-12-25 03:00:00,Mysuru,13.7,81,925.7,24.12,57,Clear,0.0,2011,12,25,3,Sunday
1,2023-08-05 22:00:00,Anand,27.6,86,1002.0,40.68,100,Cloudy,0.0,2023,8,5,22,Saturday
2,2018-05-21 05:00:00,Bharuch,27.5,90,1002.3,46.80,0,Clear,0.0,2018,5,21,5,Monday
3,2026-01-24 14:00:00,New_Delhi,16.4,46,996.7,37.08,6,Clear,0.0,2026,1,24,14,Saturday
4,2024-01-30 08:00:00,Mangaluru,25.6,64,1012.8,30.96,98,Cloudy,0.0,2024,1,30,8,Tuesday

In [10]:
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Summer"
    elif month in [6, 7, 8]:
        return "Monsoon"
    else:
        return "Post-Monsoon"

df["Season"] = df["Month"].apply(get_season)

In [11]:
df[["Month","Season"]].head(15)

    Month        Season
0      12        Winter
1       8       Monsoon
2       5        Summer
3       1        Winter
4       1        Winter
5       2        Winter
6      11  Post-Monsoon
7       6       Monsoon
8       3        Summer
9       5        Summer
10      4        Summer
11     11  Post-Monsoon
12     10  Post-Monsoon
13      4        Summer
14      7       Monsoon

In [12]:
from sklearn.preprocessing import LabelEncoder
import joblib

# Create encoders
le_city = LabelEncoder()
le_weather = LabelEncoder()
le_day = LabelEncoder()
le_season = LabelEncoder()

# Fit on ORIGINAL text columns
le_city.fit(df["City"])
le_weather.fit(df["Weather"])
le_day.fit(df["DayOfWeek"])
le_season.fit(df["Season"])

# Save encoders BEFORE transforming
from pathlib import Path

ROOT = Path.cwd().parent

joblib.dump(le_city, ROOT / "models" / "le_city.pkl")
joblib.dump(le_weather, ROOT / "models" / "le_weather.pkl")
joblib.dump(le_day, ROOT / "models" / "le_day.pkl")
joblib.dump(le_season, ROOT / "models" / "le_season.pkl")

print("Encoders saved successfully!")

Encoders saved successfully!

In [13]:

from pathlib import Path
import joblib

ROOT = Path.cwd().parent

joblib.dump(le_city, ROOT / "models" / "le_city.pkl")

['C:\\Users\\snowpiercer\\Desktop\\WeatherPredictionProject\\models\\le_city.pkl']

In [14]:
import sklearn
print(sklearn.__version__)

1.9.0

In [15]:
import sys
print(sys.executable)

C:\Users\snowpiercer\AppData\Local\Programs\Python\Python313\python.exe

In [16]:
import sklearn
print(sklearn.__version__)

1.9.0

In [17]:
import sys
print(sys.executable)

C:\Users\snowpiercer\AppData\Local\Programs\Python\Python313\python.exe

In [18]:
from sklearn.preprocessing import LabelEncoder

le_city = LabelEncoder()
le_weather = LabelEncoder()
le_day = LabelEncoder()
le_season = LabelEncoder()

df["City"] = le_city.fit_transform(df["City"])
df["Weather"] = le_weather.fit_transform(df["Weather"])
df["DayOfWeek"] = le_day.fit_transform(df["DayOfWeek"])
df["Season"] = le_season.fit_transform(df["Season"])

In [19]:
if "Date" in df.columns:
    df.drop("Date", axis=1, inplace=True)

In [20]:
df.head()

,City,Temperature,Humidity,Pressure,Wind_Speed,Cloud_Cover,Weather,Rainfall,Year,Month,Day,Hour,DayOfWeek,Season
0,31,13.7,81,925.7,24.12,57,0,0.0,2011,12,25,3,3,3
1,4,27.6,86,1002.0,40.68,100,1,0.0,2023,8,5,22,2,0
2,8,27.5,90,1002.3,46.80,0,0,0.0,2018,5,21,5,1,2
3,34,16.4,46,996.7,37.08,6,0,0.0,2026,1,24,14,2,3
4,29,25.6,64,1012.8,30.96,98,1,0.0,2024,1,30,8,5,3

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   City         10000 non-null  int64
 1   Temperature  10000 non-null  float64
 2   Humidity     10000 non-null  int64
 3   Pressure     10000 non-null  float64
 4   Wind_Speed   10000 non-null  float64
 5   Cloud_Cover  10000 non-null  int64
 6   Weather      10000 non-null  int64
 7   Rainfall     10000 non-null  float64
 8   Year         10000 non-null  int32
 9   Month        10000 non-null  int32
 10  Day          10000 non-null  int32
 11  Hour         10000 non-null  int32
 12  DayOfWeek    10000 non-null  int64
 13  Season       10000 non-null  int64
dtypes: float64(4), int32(4), int64(6)
memory usage: 937.6 KB

In [22]:
X = df.drop("Temperature", axis=1)

y = df["Temperature"]

In [23]:
print(X.shape)
print(y.shape)

(10000, 13)
(10000,)

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [25]:
print("Training:", X_train.shape)
print("Testing :", X_test.shape)

Training: (8000, 13)
Testing : (2000, 13)

In [26]:
if 'Visibility' in df.columns:
    df.drop('Visibility', axis=1, inplace=True)
df.to_csv(ROOT / 'dataset' / 'weather_featured.csv', index=False)

In [27]:
print(X.columns.tolist())

['City', 'Humidity', 'Pressure', 'Wind_Speed', 'Cloud_Cover', 'Weather', 'Rainfall', 'Year', 'Month', 'Day', 'Hour', 'DayOfWeek', 'Season']

In [28]:
import joblib

joblib.dump(le_city, "../models/le_city.pkl")
joblib.dump(le_weather, "../models/le_weather.pkl")
joblib.dump(le_day, "../models/le_day.pkl")
joblib.dump(le_season, "../models/le_season.pkl")

print("Encoders saved successfully!")

Encoders saved successfully!